name: flake8

on: [push]

jobs:
  analyze:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        module: ["00", "01"]


    steps:
      - uses: actions/checkout@v3

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 Python_Module_${{ matrix.module }} --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 Python_Module_${{ matrix.module }} --count --max-complexity=6 --statistics
